export { AdminsEndpoint } from "./admins";
export { BloodTypesEndpoint } from "./bloodTypes";
export { ClinicEndpoint } from "./clinic";
export { InsuranceTypesEndpoint } from "./insuranceTypes";
export { MedicsEndpoint } from "./medics";
export { PatientsEndpoint } from "./patients";
export { PingEndpoint } from "./ping";
export { ScheduleEndpoint } from "./schedule";
export { SpecialtiesEndpoint } from "./specialties";
